name: quickcheck
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  collection: 1.18.0
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.4.1
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: 6.1.0
  intl: 0.19.0
  json_path: 0.7.2
  page_transition: 2.1.0
  path_provider: 2.1.4
  provider: 6.1.2
  shared_preferences: 2.3.2
  sqflite: 2.3.3+1
  sqflite_common: 2.5.4+3
  timeago: 3.6.1
  url_launcher: 6.3.0
  bottom_navbar_with_indicator: ^0.0.9
  image_picker: ^1.0.4
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_lints: 4.0.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
